[[redirects]]
  from = "/api/*"
  to = "https://fit-gen-fbwd.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"
