version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: fitgen-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI= mongodb+srv://sumitsonar519:KTAwImW1o7BNtZJx@cluster0.z8ici.mongodb.net
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: fitgen-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
